language: c
sudo: required
addons:
  apt:
    packages:
      - libcr-dev 
      - mpich2 
      - libmpich-dev
      - mpich2-doc
script:
  - cd build
  - wget http://download847.mediafire.com/yytddnym8scg/tsu144gjmu29xj3/rgbdata-temp
  - cd ..
  - mpicc ./src/rgb_histogram.c -o ./build/rgbhistogram
  - cd build
  - ls
  - mpirun -n 2 ./build/rgbhistogram | tee ./output/rgbhistogram
  - cat ./output/rgbhistogram
